# Generated by Django 2.2.4 on 2020-01-23 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('house_type', models.CharField(max_length=1000)),
                ('meters', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('parkings', models.IntegerField()),
                ('location', models.CharField(max_length=1000)),
                ('locality', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='')),
                ('estate', models.CharField(max_length=1000)),
                ('starred', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.EmailField(default=None, max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilidapp.House')),
            ],
        ),
    ]
