# Generated by Django 2.2.4 on 2020-01-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kilidapp.Profile'),
        ),
    ]
