# Generated by Django 2.2.4 on 2020-01-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0002_house_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
