# Generated by Django 2.2.4 on 2020-01-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0004_auto_20200123_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kilidapp.Profile'),
        ),
    ]
