# Generated by Django 2.2.4 on 2020-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0005_auto_20200123_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bookmarked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='starred',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
