# Generated by Django 2.2.4 on 2020-01-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0008_house_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pic',
            field=models.ImageField(null=True, upload_to='house_image'),
        ),
    ]
