# Generated by Django 2.2.4 on 2020-01-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0010_auto_20200123_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(null=True, upload_to='house_image')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilidapp.House')),
            ],
        ),
    ]
