# Generated by Django 2.2.4 on 2020-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0012_auto_20200123_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='pic',
            field=models.ImageField(default=None, null=True, upload_to='house_image'),
        ),
    ]
