# Generated by Django 2.2.4 on 2020-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0013_auto_20200124_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='bookmarked',
        ),
        migrations.AddField(
            model_name='house',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarks', to='kilidapp.Profile'),
        ),
    ]
