# Generated by Django 2.2.4 on 2020-01-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilidapp', '0015_auto_20200124_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
